### ISSUE TITLE
学習データの色の特徴量の主成分分析を行い次元圧縮を行う

### ISSUE THREAD

**Issue by Mishima-Ryuji** [jphacks/B_2207#10]
jupyter notebookで実験して何次元にするかを決めてその変換（行列）を求めて，その行列をCSVに吐き出しておくのが良さそう．実際にユーザが撮影した服の色の特徴量が与えられたら，それを上記の行列で変換して圧縮空間に写像する感じになると思う．jupyter notebookはレビューのときに確認したいから削除しないで残しておいてほしい．

**Comment by ikeike-da** [comment]
scikit-learn の PCA クラスの transform メソッドで簡単に変換行列得られたから，後はcsvに吐き出すだけになってる．
