### ISSUE TITLE
学習データの主成分を尤もらしい混合ガウス分布で表して評価値を計算する

### ISSUE THREAD

**Issue by Mishima-Ryuji** [jphacks/B_2207#11]
## 概要
主成分空間に写像された学習データを混合分布で最尤推定する．混合パラメータやそれぞれの分布の平均分散を求めるためには，EMアルゴリズムが使えそう．得た混合分布pを使って，ユーザの服の色の特徴量に対応する値を計算して評価値とするのが良いかなと思う．

**Comment by ikeike-da** [comment]
https://qiita.com/ctgk/items/22ce61fc0ffbc12c64d1#%E5%85%A8%E4%BD%93%E3%81%AE%E3%82%B3%E3%83%BC%E3%83%89
のコードがそのまま使えそうwモデルを学習するクラスも評価値を返してくれるメソッドもそのままあるから，実装の必要なさそう
